function knn_cv_createBarGraph(yvector1)
%CREATEFIGURE1(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 14-Nov-2017 01:28:57

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
bar(yvector1);

box(axes1,'on');
